import geopandas as gpd
import pandas as pd
import collections.abc
import json
import numpy as np
import itertools
import shapely
import zipfile
import shutil
import contextlib
import io

from pathlib import Path

from svalbardradar.tools import stats, paths


def format_float(number: float, decimals: int = 1) -> str:
    """

    Examples
    --------
    >>> format_float(1.3456)
    '1.35'
    >>> format_float(1.3)
    '1.30'
    """
    rounded = str(round(float(number), decimals))

    if "." not in rounded:
        rounded += "." + "0" * decimals
    elif (n_zeros := len(rounded.split(".")[-1])) != decimals:
        rounded += "0" * (decimals - n_zeros)

    return rounded


def rec_update_dict(dictionary: dict, new: dict, i: int = 0, max_i: int = 20):
    if i == max_i:
        raise RecursionError("Max recursion limit reached")

    for key, value in new.items():
        if isinstance(value, collections.abc.Mapping):
            dictionary[key] = rec_update_dict(
                dictionary.get(key, {}),
                value,
                i=i + 1,
                max_i=max_i,  # pyright: ignore[reportArgumentType]
            )
        else:
            dictionary[key] = value
    return dictionary


def rec_to_tex_macros(
    dictionary: dict | collections.abc.Mapping, pre_key: str = "", i: int = 0, max_i: int = 20
) -> list[str]:
    if i == max_i:
        raise RecursionError("Max recursion limit reached")

    macros = []

    if i == 0:
        macros.append("% Autogenerated macro file.\n")
    for key, value in dictionary.items():
        new_key = ".".join([pre_key, key]) if len(pre_key) > 0 else key
        if isinstance(value, collections.abc.Mapping):
            macros += rec_to_tex_macros(value, pre_key=new_key, i=i + 1, max_i=max_i)
        else:
            macros += [
                f"% {new_key}",
                "\\def\\dataX" + new_key.replace(".", "X").replace("_", "") + "/{" + str(value) + "}",
            ]

    return macros


def format_values(obj: object, i: int = 0, max_i: int = 20) -> object:
    if isinstance(obj, str):
        return obj
    if hasattr(obj, "dtype"):
        obj = obj.item()
    if isinstance(obj, float):
        formatted = format_float(obj)
        return formatted
    if isinstance(obj, collections.abc.Mapping):
        new_obj = {}
        for key, value in obj.items():
            new_obj[key] = format_values(value, i=i + 1, max_i=max_i)
        return new_obj
    elif isinstance(obj, collections.abc.Sequence):
        new_obj = []
        for value in obj:
            new_obj.append(format_values(value, i=i + 1, max_i=max_i))

    return obj


def record_information(new_info: dict[str, object] | None = None) -> dict[str, object]:
    info_path = Path("tables/statistics.json")
    info_tex_path = info_path.with_suffix(".tex")

    if info_path.is_file():
        with open(info_path) as infile:
            info = json.load(infile)
    else:
        info = {}

    if new_info is not None:
        info = rec_update_dict(info, new_info)

        info_path.parent.mkdir(exist_ok=True, parents=True)
        with open(info_path, "w") as outfile:
            json.dump(
                format_values(info),
                outfile,
                indent=2,
            )
        with open(info_path) as infile:
            info = json.load(infile)

        info_tex = rec_to_tex_macros(info)
        with open(info_tex_path, "w") as outfile:
            outfile.write("\n".join(info_tex))

    return info


def glacier_table():
    import svalbardradar.interpretations
    import svalbardradar.figures

    data = svalbardradar.interpretations.merge_all_interpretations()

    data["glacier"] = data["radar_key"].str.split("-", expand=True).iloc[:, 0]

    distances = data.groupby(["glacier", "radar_key"])["distance"].max().groupby("glacier").sum()

    outlines = svalbardradar.figures.get_svalbard_glaciers()
    glaciers = gpd.read_file("shapes/glacier_locations.geojson")

    glaciers = gpd.sjoin(glaciers, outlines, how="left", predicate="intersects")
    glaciers["geometry"] = outlines.loc[glaciers["index_right"].values, "geometry"].values

    glaciers["track_length"] = distances.loc[glaciers["key"]].values / 1e3

    record_information({"total_profile_length_km": int(round(glaciers["track_length"].sum()))})
    glaciers["track_length"] = glaciers["track_length"].round().astype(int)
    glaciers["area"] = (glaciers["Shape_Area"] * 1e-6).round().astype(int)

    glaciers["zrange"] = (
        glaciers["minZ"].round().astype(int).astype(str) + "–" + glaciers["maxZ"].round().astype(int).astype(str)
    )

    cols = {
        "name": "Glacier",
        "area": "Area (km²)",
        "zrange": "Elevation range (m a.s.l.)",
        "track_length": "GPR profile length (km)",
        "last_surge": "Last surge",
    }

    no_date = "No date$^{[2]}$"
    surging = {
        "etonbreen": "2023$^{[1]}$",
        "von_postbreen": "1870$^{[2]}$",
        "elfenbeinbreen": "1903$^{[2]}$",
        "jinnbreen": no_date,
        "moysalbreen": "1925$^{[2]}$",
        "lofthusbreen": "1896$^{[3]}$",
        "dronbreen": "1896$^{[3]}$",
        "scott_turnerbreen": "1914$^{[3]}$",
        "bergmesterbreen": no_date,
        "rugaasfonna": no_date,
        "svellnosbreen": no_date,
        "kroppbreen": "2000s$^{[4]}$",
        "edvardbreen": "$\\sim$2025$^{[1]}$",
        "vallakrabreen": "2022$^{[1]}$",
        "mettebreen": no_date,
        "ragna_mariebreen": no_date,
        "filantropbreen": no_date,
        "antoniabreen": no_date,
        "finsterwalderbreen": "1914$^{[2]}$",
    }
    glaciers["last_surge"] = glaciers["key"].map(lambda k: surging.get(k, "-"))

    tex_table = r"\begin{tabular}{l" + "c" * (len(cols) - 1) + "}\n"
    tex_table += "&".join((r"\textbf{" + v + "}" for v in cols.values())) + "\\\\\n\\midrule\n"

    for _, glacier in glaciers.sort_values("Y_cent", ascending=False).iterrows():
        tex_table += "&".join((str(glacier[col]) for col in cols))
        tex_table += "\\\\\n"

    tex_table += r"\end{tabular}"

    out_path = Path("tables/glacier_table.tex")
    out_path.parent.mkdir(exist_ok=True, parents=True)
    out_path.write_text(tex_table)
    print(tex_table)


def contribution_stats():
    active_user_dirs = list((Path(__file__).parent.parent / "submitted").iterdir())

    n_submissions_per_radargram = {}
    n_submissions_per_user = {}

    n_active_users = 0
    for user_dir in active_user_dirs:
        if not user_dir.is_dir():
            continue
        n_active_users += 1

        n_submissions_per_user[user_dir.stem] = 0

        for radargram_dir in user_dir.iterdir():
            if not radargram_dir.is_dir():
                continue

            # This was removed early on but still exists in the data
            if radargram_dir.stem == "slakbreen-20220330-DAT_0252_A1_1":
                continue

            n_submissions_per_user[user_dir.stem] += 1

            if radargram_dir.stem not in n_submissions_per_radargram:
                n_submissions_per_radargram[radargram_dir.stem] = 1
            else:
                n_submissions_per_radargram[radargram_dir.stem] += 1

    n_sub_arr = np.array(list(n_submissions_per_radargram.values()))

    # avg_submissions_per_radar = n_sub_arr.mean()

    # print(f"N active users: {n_active_users}")
    # print(f"Avg submissions per user: {np.mean(list(n_submissions_per_user.values())):.0f}")
    # print(f"Total amount of submissions: {sum(n_submissions_per_radargram.values())}")
    # print(f"Avg submissions per radargram: {avg_submissions_per_radar:.1f}")

    # print("\nNumber of contributions per person: ")
    # for user, vals in sorted(n_submissions_per_user.items(), key=lambda item: item[1], reverse=True):
    #     print(f"\t{user}:  {vals}")

    record_information(
        {
            "contributions": {
                "n_active_users": n_active_users,
                "avg_submissions_per_user": int(round(np.mean(list(n_submissions_per_user.values())))),
                "n_total_submissions": n_sub_arr.sum(),
                "avg_submissions_per_rgm": n_sub_arr.mean(),
                "min_per_rgm": n_sub_arr.min(),
                "max_per_rgm": n_sub_arr.max(),
            }
        }
    )


def cts_transition_steepness():
    import svalbardradar.interpretations
    import matplotlib.pyplot as plt

    all_data = svalbardradar.interpretations.merge_all_interpretations()

    radar_keys = {
        "mettebreen-20230305-DAT_0235_A1_8": [4300, 6300],
        # "filantropbreen-20240406-DAT_0372_A1_1",
        # "moysalbreen-20220222-DAT_0749_A1_1",
        # "rugaasfonna-20220218-DAT_0723_A1_1",
        # "lofthusbreen-20250326-DAT_0057_A1_1",
        # "finsterwalderbreen-20250407-DAT_0171_A1_1"],
        "ragna_mariebreen-20240412-DAT_0404_A1_1": [0, 10000],
        # "winsnesbreen-20240503-DAT_0014_A1_1",
        "dronbreen-20230220-DAT_0009_A1_1": [0, 2500],
        # # "dronbreen-20250327-DAT_0065_A1_1",
        "kroppbreen-20230228-DAT_0042_A1_1": [1000, 4500],
        "slakbreen-20240310-DAT_0286_A1_1": [6000, 14000],
        "edvardbreen-20240411-DAT_0396_A1_1": [8000, 13500],
        "vallakrabreen-20210513-DAT_0014_A1_31": [5900, 6200],
    }

    transitions = {}

    for radar_key in radar_keys:
        bounds = radar_keys[radar_key]

        data = all_data[
            (all_data["radar_key"] == radar_key)
            & (all_data["distance"] > bounds[0])
            & (all_data["distance"] < bounds[1])
        ]

        if data["temperate_frac"].iloc[0] > data["temperate_frac"].iloc[-1]:
            data = data.iloc[::-1]
            # data["distance"] = data["distance"].max() - data["distance"]

        # data["temperate_frac"] -= data["temperate_frac"].min()
        # data["temperate_frac"] /= data["temperate_frac"].max()
        # fig, axes = plt.subplots(2, 1, sharex=True)
        # axes[0].plot(data["distance"], data["temperate_frac"])
        # axes[1].plot(data["distance"], data["thickness"])
        # plt.show()

        transition_start = data[data["temperate_frac"] > 0.05].iloc[0]
        transition_end = data[data["temperate_frac"] >= (0.95 if "slakbreen" not in radar_key else 0.93)].iloc[0]
        dist = sorted([transition_start["distance"], transition_end["distance"]])

        mean_thickness = data.loc[(data["distance"] > dist[0]) & (data["distance"] < dist[1]), "thickness"].mean()

        distance = dist[1] - dist[0]
        slope = np.rad2deg(np.arctan(mean_thickness / distance))

        transitions[radar_key.split("-")[0]] = {
            "thickness": int(round(mean_thickness)),
            "distance": int(round(distance)),
            "slope": int(round(slope)),
        }
        # slopes.append({"glacier": , "thickness": mean_thickness, "distance": distance, "slope": slope})
        # print(mean_thickness, distance, slope)

        continue
        fig, axes = plt.subplots(2, 1, sharex=True)
        axes[0].plot(data["distance"], data["temperate_frac"])
        axes[1].plot(data["distance"], data["thickness"])

        for axis in axes:
            ylim = axis.get_ylim()
            axis.vlines(transition_start["distance"], *ylim, color="green", label="start (5%)")
            axis.vlines(transition_end["distance"], *ylim, color="red", label="stop (95%)")

        plt.legend()
        plt.show()
        print(data)

    record_information(
        {
            "cts": {
                "transitions": transitions,
            }
        }
    )


def data_stats():
    import svalbardradar.interpretations

    data = svalbardradar.interpretations.merge_all_interpretations()

    antenna_alias = {"25 MHz": "low", "100 MHz": "high"}
    per_antenna_stats = {}
    for antenna, a_data in data.groupby("antenna"):
        if antenna not in antenna_alias:
            continue

        e_user = a_data["thickness_user_nmad"].median()
        wavelength = 168 / int(antenna.split(" ")[0])
        per_antenna_stats[antenna_alias[antenna]] = {
            "median": e_user,
            "perwavelength": int(round(100 * e_user / wavelength)),
        }

    svalbardradar.analysis.record_information(
        {
            "perantenna": {
                "e_user": per_antenna_stats,
            }
        }
    )

    cts_relevant = (data["temperate_frac"] > 0.1) & (data["temperate_frac"] < 0.9)

    high_bad_concensus_frac = np.count_nonzero(data["thickness_user_nmad"] > 20) / data.shape[0]
    record_information(
        {
            "data": {
                "bad_consensus_frac": int(round(high_bad_concensus_frac * 1000)),
                "uncertainty": {
                    "bed": data["thickness_nmad"].median(),
                    "bed_pm": stats.nmad(data["thickness_nmad"]),
                    "cts": data.loc[cts_relevant, "temperate_nmad"].median(),
                    "cts_pm": stats.nmad(data.loc[cts_relevant, "temperate_nmad"]),
                    "e_gpr": data["thickness_gpr_uncertainty"].median(),
                    "e_gpr_pm": stats.nmad(data["thickness_gpr_uncertainty"]),
                    "e_gnss": data["thickness_gnss_uncertainty"].median(),
                    "e_gnss_pm": stats.nmad(data["thickness_gnss_uncertainty"]),
                    "e_user": data["thickness_user_nmad"].median(),
                    "e_user_pm": stats.nmad(data["thickness_user_nmad"]),
                },
            },
            "temperate_fractions": {
                "average": round(100 * (data["temperate_frac"] * data["thickness"]).sum() / data["thickness"].sum())

            }
        }
    )


def embargoed_radar_keys() -> list[str]:
    return [
        "mettebreen-20230305-DAT_0229_A1_1",
        "mettebreen-20230305-DAT_0235_A1_8",
        "ragna_mariebreen-20230305-DAT_0067_A1_1",
        "ragna_mariebreen-20230305-DAT_0068_A1_3",
        "edvardbreen-20230305-DAT_0230_A1_1",
        "edvardbreen-20230305-DAT_0234_A1_1",
        "edvardbreen-20230305-DAT_0232_A1_1",
        "rabotbreen-20250402-DAT_0068_A1_1",
        "rabotbreen-20250402-DAT_0071_A1_1",
    ]


def make_data_publication(glaciers: list[str] | None = ["filantropbreen", "fimbulisen"], use_embargo: bool = True):
    import svalbardradar.interpretations
    import svalbardradar.process_radar
    import xarray as xr
    import subprocess

    all_data = svalbardradar.interpretations.merge_all_interpretations()

    # Make sure that the keys are spelled correctly (i.e. they all occur somewhere in the data)
    embargo_list = embargoed_radar_keys()
    assert np.isin(embargo_list, all_data["radar_key"]).all()

    pub_dir = Path("data_pub")

    all_data["glacier"] = all_data["radar_key"].str.split("-", expand=True).iloc[:, 0]

    if glaciers is None:
        glaciers: list[str] = all_data["glacier"].unique().tolist()  # pyright: ignore[reportAssignmentType]
    else:
        all_data = all_data[all_data["glacier"].isin(glaciers)]

    all_raw_dirs = svalbardradar.process_radar.get_paths()
    report_paths = []

    with contextlib.ExitStack() as stack:
        csvs_zipfile = stack.enter_context(zipfile.ZipFile(pub_dir / "thickness_cts_points_csv.zip", mode="w"))
        dem_paths = set()
        for glacier, per_glacier in all_data.groupby("glacier"):
            glacier = str(glacier)
            radargrams_zipfile = stack.enter_context(zipfile.ZipFile(pub_dir / f"radargrams-{glacier}.zip", mode="w"))

            for radar_key, per_key in per_glacier.groupby("radar_key"):
                radar_key = str(radar_key)

                embargoed = radar_key in embargo_list and use_embargo
                _, date_str, file_stem = radar_key.split("-")

                # Write a thickness/cts csv for the key
                data_bytes = io.BytesIO()
                per_key.to_csv(data_bytes, index=False)
                csvs_zipfile.writestr(f"thickness_cts_points_{radar_key}.csv", data_bytes.getvalue())
                del data_bytes

                # Make sure to include the DEM for this key
                dem_paths.add(svalbardradar.process_radar.get_dem_path(radar_key))

                # Define filepaths to copy over to the data pub
                thumbnail_path = Path(f"web/static/radargrams/{glacier}/{date_str}/{file_stem}/thumbnail.jpg")
                report_path = Path(f"figures/all_interpretations_perprofile/interpretations_{radar_key}.pdf")
                processed_path = paths.processed_radar_path(radar_key)

                report_paths.append(str(report_path.absolute()))

                # Add all the raw data filenames
                file_stems = []
                if not radar_key.endswith("_1"):
                    with xr.open_dataset(processed_path) as dataset:
                        for filepath in map(Path, dataset.attrs["original_filepaths"]):
                            file_stems.append(filepath.stem)

                # Construct filepaths for all the raw data
                filepaths = []
                for file_stem in file_stems:
                    try:
                        rd3_filepath = next(
                            itertools.chain(*[d.rglob(f"*{file_stem}.rd3") for d in all_raw_dirs[glacier][date_str]])
                        )
                    except StopIteration:
                        raise ValueError(f"Cannot find file {file_stem}")

                    filepaths += [rd3_filepath, rd3_filepath.with_suffix(".cor"), rd3_filepath.with_suffix(".rad")]

                # Make a track file for the key
                lines = []
                for part_idx, per_part in per_key.groupby("part_idx"):
                    if per_part.shape[0] < 2:
                        continue
                    lines.append(
                        {
                            "geometry": shapely.LineString(per_part[["easting", "northing"]]),
                            "part_idx": part_idx,
                        }
                    )
                track = gpd.GeoDataFrame.from_records(lines)
                track.set_geometry("geometry", crs=per_key.crs, inplace=True)
                track["length"] = track["geometry"].length

                if not embargoed:
                    # Add the raw data to the zipfile
                    rawdata_bytes = io.BytesIO()
                    with zipfile.ZipFile(rawdata_bytes, mode="w") as zip_file:
                        for filepath in filepaths:
                            zip_file.write(filepath, arcname=filepath.name)
                    radargrams_zipfile.writestr(f"{radar_key}/{radar_key}_raw_data.zip", rawdata_bytes.getvalue())
                    del rawdata_bytes

                # Add the track to the zipfile
                track_bytes = io.BytesIO()
                track.to_file(track_bytes, driver="GeoJSON")
                radargrams_zipfile.writestr(f"{radar_key}/{radar_key}_track.geojson", track_bytes.getvalue())
                del track_bytes

                radargrams_zipfile.write(thumbnail_path, f"{radar_key}/{radar_key}_thumbnail.jpg")
                radargrams_zipfile.write(report_path, f"{radar_key}/{radar_key}_interpretation_report.pdf")
                if not embargoed:
                    radargrams_zipfile.write(processed_path, f"{radar_key}/{radar_key}_processed.nc")

    subprocess.run(["pdfunite"] + report_paths + [str(pub_dir / "interpretation_report.pdf")], check=True)

    with zipfile.ZipFile(pub_dir / "dems.zip", mode="w") as zip_file:
        for dem_path in dem_paths:
            zip_file.write(dem_path, dem_path.name)

    with zipfile.ZipFile(pub_dir / "interpretation_lines.zip", mode="w") as zip_file:
        for filepath in Path("submitted").rglob("*.json"):
            if not any(glacier in filepath.parts[-2] for glacier in glaciers):
                continue
            zip_file.write(filepath, "/".join(filepath.parts[-3:]))

    all_data.to_feather(pub_dir / "thickness_cts_points.arrow")
    shutil.copyfile("data_pub_README.md", pub_dir / "README.md")
    shutil.copyfile("funding.csv",  pub_dir / "funding.csv")
